name: windows-test
on:
  pull_request:
    branches:
     - main
  push:
    branches:
     - main
jobs:
  grammar-test:
    name: Grammar Test
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: "true"
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Grammar Test on Windows
        run: .\internal\scripts\test_grammar.bat

  unit-test:
    name: Unit Test
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: "true"
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Unit Test on Windows
        run: .\internal\scripts\test_unit.bat

  run-test:
    name: Run Test
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: "true"
      - name: Run
        shell: bash
        run: |
          python3 -m pip install -r .\\kclvm\\scripts\\requirements.txt
          python3 -m kclvm .\\samples\\hello.k
          python3 -m kclvm .\\samples\\hello.k --target native
